//! Aperiodic deterministic sequences — Penrose, Fibonacci, quasicrystal.
//!
//! These sequences are aperiodic (never repeat exactly) but fully determined
//! by local rules. The Fibonacci word is the simplest example: a substitution
//! sequence 0→01, 1→0 that produces the golden ratio in its character frequencies.

use serde::{Serialize, Deserialize};
use crate::golden::GoldenRatio;

/// The Fibonacci word: an infinite aperiodic sequence over {0, 1}.
///
/// Generated by the substitution rule: 0 → 01, 1 → 0
/// Starting from "0", successive iterations produce:
/// 0, 01, 010, 01001, 01001010, 0100101001001, ...
///
/// Properties:
/// - Aperiodic (never repeats)
/// - Deterministic (completely determined by local substitution rules)
/// - 0s and 1s appear in ratio φ:1 (golden ratio)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FibonacciSequence {
    /// The finite prefix of the infinite Fibonacci word.
    pub word: Vec<u8>,
    /// Number of substitution steps applied.
    pub generation: u32,
}

impl FibonacciSequence {
    /// Create the initial Fibonacci word "0".
    pub fn new() -> Self {
        Self { word: vec![0], generation: 0 }
    }

    /// Apply one substitution step: 0→01, 1→0.
    pub fn substitute(&self) -> Self {
        let new_word: Vec<u8> = self.word.iter().flat_map(|&c| {
            match c {
                0 => vec![0, 1],
                1 => vec![0],
                _ => vec![],
            }
        }).collect();
        Self { word: new_word, generation: self.generation + 1 }
    }

    /// Apply n substitution steps.
    pub fn substitute_n(&self, n: u32) -> Self {
        let mut seq = self.clone();
        for _ in 0..n {
            seq = seq.substitute();
        }
        seq
    }

    /// Count occurrences of 0 and 1.
    pub fn counts(&self) -> (usize, usize) {
        let zeros = self.word.iter().filter(|&&c| c == 0).count();
        let ones = self.word.len() - zeros;
        (zeros, ones)
    }

    /// Ratio of 0s to 1s should approach φ.
    pub fn ratio(&self) -> f64 {
        let (zeros, ones) = self.counts();
        if ones == 0 { return f64::INFINITY; }
        zeros as f64 / ones as f64
    }

    /// Length of the word.
    pub fn len(&self) -> usize {
        self.word.len()
    }

    pub fn is_empty(&self) -> bool {
        self.word.is_empty()
    }

    /// Check if the word contains a specific pattern.
    pub fn contains(&self, pattern: &[u8]) -> bool {
        if pattern.len() > self.word.len() { return false; }
        self.word.windows(pattern.len()).any(|w| w == pattern)
    }

    /// Verify aperiodicity: the word should not have a period less than its length.
    pub fn is_aperiodic(&self) -> bool {
        if self.word.len() < 4 { return true; }
        for period in 1..self.word.len() / 2 {
            if self.word.len() % period == 0 {
                let mut periodic = true;
                for i in period..self.word.len() {
                    if self.word[i] != self.word[i % period] {
                        periodic = false;
                        break;
                    }
                }
                if periodic {
                    return false;
                }
            }
        }
        true
    }
}

/// A Penrose sequence: a 1D projection of the 2D Penrose tiling.
///
/// By projecting the vertices of a Penrose tiling onto a line at the golden
/// angle, we get a 1D quasicrystal sequence with two interval lengths
/// (L and S) in the ratio φ:1.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PenroseSequence {
    /// Long interval length.
    pub long: f64,
    /// Short interval length.
    pub short: f64,
    /// The sequence: true = long interval, false = short interval.
    pub intervals: Vec<bool>,
}

impl PenroseSequence {
    /// Create a Penrose sequence by substitution: L → LS, S → L.
    pub fn new(n_substitutions: u32) -> Self {
        let long = GoldenRatio::PHI;
        let short = 1.0;
        let mut intervals = vec![true]; // Start with L

        for _ in 0..n_substitutions {
            intervals = intervals.iter().flat_map(|&is_long| {
                if is_long { vec![true, false] } else { vec![true] }
            }).collect();
        }

        Self { long, short, intervals }
    }

    /// Total length of the sequence.
    pub fn total_length(&self) -> f64 {
        self.intervals.iter()
            .map(|&is_long| if is_long { self.long } else { self.short })
            .sum()
    }

    /// Count long and short intervals.
    pub fn counts(&self) -> (usize, usize) {
        let longs = self.intervals.iter().filter(|&&x| x).count();
        let shorts = self.intervals.len() - longs;
        (longs, shorts)
    }

    /// Ratio of long to short intervals should approach φ.
    pub fn ratio(&self) -> f64 {
        let (longs, shorts) = self.counts();
        if shorts == 0 { return f64::INFINITY; }
        longs as f64 / shorts as f64
    }

    /// Number of intervals.
    pub fn len(&self) -> usize {
        self.intervals.len()
    }

    pub fn is_empty(&self) -> bool {
        self.intervals.is_empty()
    }

    /// Verify aperiodicity.
    pub fn is_aperiodic(&self) -> bool {
        if self.intervals.len() < 4 { return true; }
        for period in 1..self.intervals.len() / 2 {
            if self.intervals.len() % period == 0 {
                let mut periodic = true;
                for i in period..self.intervals.len() {
                    if self.intervals[i] != self.intervals[i % period] {
                        periodic = false;
                        break;
                    }
                }
                if periodic {
                    return false;
                }
            }
        }
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fibonacci_initial() {
        let fib = FibonacciSequence::new();
        assert_eq!(fib.word, vec![0]);
        assert_eq!(fib.generation, 0);
    }

    #[test]
    fn test_fibonacci_substitute() {
        let fib = FibonacciSequence::new();
        let s1 = fib.substitute();
        assert_eq!(s1.word, vec![0, 1]);
        assert_eq!(s1.generation, 1);

        let s2 = s1.substitute();
        assert_eq!(s2.word, vec![0, 1, 0]);
        assert_eq!(s2.generation, 2);

        let s3 = s2.substitute();
        assert_eq!(s3.word, vec![0, 1, 0, 0, 1]);
        assert_eq!(s3.generation, 3);
    }

    #[test]
    fn test_fibonacci_ratio() {
        let fib = FibonacciSequence::new().substitute_n(15);
        let ratio = fib.ratio();
        assert!(GoldenRatio::is_golden(ratio, 0.1));
    }

    #[test]
    fn test_fibonacci_length_is_fib_number() {
        // F(n) where F(1)=1, F(2)=2, F(3)=3, F(4)=5, F(5)=8, ...
        // The lengths of the Fibonacci word are Fibonacci numbers
        let fib = FibonacciSequence::new().substitute_n(5);
        assert_eq!(fib.len(), 13); // F(7) = 13
    }

    #[test]
    fn test_fibonacci_aperiodic() {
        let fib = FibonacciSequence::new().substitute_n(10);
        assert!(fib.is_aperiodic());
    }

    #[test]
    fn test_fibonacci_counts() {
        let fib = FibonacciSequence::new().substitute_n(10);
        let (zeros, ones) = fib.counts();
        assert!(zeros > ones); // 0s are more frequent
    }

    #[test]
    fn test_fibonacci_contains() {
        let fib = FibonacciSequence::new().substitute_n(8);
        assert!(fib.contains(&[0, 1]));
        assert!(fib.contains(&[1, 0]));
        // "11" never appears in the Fibonacci word
        assert!(!fib.contains(&[1, 1]));
    }

    #[test]
    fn test_fibonacci_no_11() {
        // The Fibonacci word never contains "11"
        let fib = FibonacciSequence::new().substitute_n(15);
        assert!(!fib.contains(&[1, 1]));
    }

    #[test]
    fn test_fibonacci_no_000() {
        // The Fibonacci word never contains "000"
        let fib = FibonacciSequence::new().substitute_n(15);
        assert!(!fib.contains(&[0, 0, 0]));
    }

    #[test]
    fn test_penrose_sequence() {
        let seq = PenroseSequence::new(5);
        assert!(seq.len() > 0);
    }

    #[test]
    fn test_penrose_ratio() {
        let seq = PenroseSequence::new(12);
        let ratio = seq.ratio();
        assert!(GoldenRatio::is_golden(ratio, 0.1));
    }

    #[test]
    fn test_penrose_total_length() {
        let seq = PenroseSequence::new(5);
        assert!(seq.total_length() > 0.0);
    }

    #[test]
    fn test_penrose_aperiodic() {
        let seq = PenroseSequence::new(8);
        assert!(seq.is_aperiodic());
    }

    #[test]
    fn test_penrose_counts() {
        let seq = PenroseSequence::new(10);
        let (longs, shorts) = seq.counts();
        assert!(longs > 0);
        assert!(shorts > 0);
    }

    #[test]
    fn test_fibonacci_serialization() {
        let fib = FibonacciSequence::new().substitute_n(5);
        let json = serde_json::to_string(&fib).unwrap();
        let back: FibonacciSequence = serde_json::from_str(&json).unwrap();
        assert_eq!(back.word, fib.word);
    }

    #[test]
    fn test_penrose_serialization() {
        let seq = PenroseSequence::new(5);
        let json = serde_json::to_string(&seq).unwrap();
        let back: PenroseSequence = serde_json::from_str(&json).unwrap();
        assert_eq!(back.intervals, seq.intervals);
    }
}
